### ISSUE TITLE
Scoring is off

### ISSUE THREAD

**Issue by haralkar** [sheibeck/pendulumbot#8]
In the negative part, each circle is half a star.

when the Average Automa gets five stars and highest priviledge her points are: -1automa +2 first priv. +2+2+0 cards, resulting in 5 points. Current calculations sets them and -16, but the circles in the off the parchment (negative) are all doubled, so should be -17,5 (unless I'm also off by a bit ;-) ).

Anyway, advancing points, while off the parchment, should be halved or the distance double depending on you preference.

**Comment by sheibeck** [comment]
Wow, I totally never noticed the double spaces in the non-parchment. Ugh! Thank you for pointing that out! That is NOT very obvious at first glance, oddly enough. Fix in the works. Thanks again.

**Comment by sheibeck** [comment]
I believe I've addressed this issue now. I'm using a matrix to display scores properly when they are negative and have extrapolated -10 and lower. The automa's now start off at -16 as their score and will only move up in score every 2 VPs until they hit -1, at which point we then go up by 1 everytime. There is no zero score, we go right from -1 to 1, sooo, hopefully I have the code right now.

**Comment by haralkar** [comment]
game designers can be so in-considered to us programmers ;-)

**Comment by sheibeck** [comment]
So. True. :)
